### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/usage-monitor#1]
Add a pull request template to the project.

**Comment by ak7550** [comment]
Hey @adityabisoi , I would like to work on the issue. Please assign this to me.

**Comment by ak7550** [comment]
@adityabisoi , I have given a PR on this issue, [created a pull request template #10](https://github.com/the-browser-toolbox/usage-monitor/pull/10). Please check. Let me know if some changes are needed.
