### ISSUE TITLE
Add Popup page

### ISSUE THREAD

**Issue by aashu** [the-browser-toolbox/usage-monitor#13]
add popup page to show usage stats and add option to reset data.

**Comment by aashu** [comment]
@adityabisoi , i would like to work on this ... 
do i still need to stick with html,css and vanilla js or i can use bootstrap etc?

**Comment by adityabisoi** [comment]
It is better to work with vanilla JS and traditional HTML and CSS since not everyone is familiar with bootstrap

**Comment by aashu** [comment]
hey @adityabisoi , sorry for delay,I was busy because of exams and some other reasons..
i have added #16  PR, please review it and let me know if something is not right.
