### ISSUE TITLE
Add issue template: feature request

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/usage-monitor#2]
Add an issue template for requesting new features in the project.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @adityabisoi

**Comment by adityabisoi** [comment]
@subhangi2731 Please go ahead ;)

**Comment by Jigyasa-G** [comment]
Can you assign it to me, I want to work on it!

**Comment by adityabisoi** [comment]
@Jigyasa-G You have to comment & get assigned to an issue to start working.

**Comment by Jigyasa-G** [comment]
> @Jigyasa-G You have to comment & get assigned to an issue to start working.

Ok, I will keep that in mind
