### ISSUE TITLE
Design a new UI for the extension.

### ISSUE THREAD

**Issue by NotRohanPaul** [the-browser-toolbox/usage-monitor#21]
I am staring to work on this an test different design .

**Comment by NotRohanPaul** [comment]
![Usuage Monitor UI v1](https://user-images.githubusercontent.com/75577230/145083784-67cd577d-4d5f-4afb-9389-2395cf8da180.PNG)
Any Comment and Suggestion.

**Comment by adityabisoi** [comment]
Sure, I hope you know how extension's popup page works. This is not a regular webpage.

**Comment by NotRohanPaul** [comment]
@adityabisoi I will make some changes to the popup and options page and send you screenshot.I will make sure while changing design the functionality doesn't get changed in any way.

**Comment by NotRohanPaul** [comment]
![Usuage Monitor Options](https://user-images.githubusercontent.com/75577230/145456810-a816df1f-4d7e-4300-b14a-df6928acbe9b.PNG)
![Usuage Monitor Popup](https://user-images.githubusercontent.com/75577230/145456829-5ca3b4f4-24c9-4b66-82f4-c7b2163b930f.PNG)
@adityabisoi CAN I MAKE PULL REQUEST or any further changes is required

**Comment by adityabisoi** [comment]
You can make a PR and show the screenshots there.
