### ISSUE TITLE
Add popup page and background script

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/usage-monitor#6]
Add a simple popup page showing `Hello World` and a background script to the extension. These will be the initial setup files, the popup page is for UI, and the background script is for handling the business logic of the extension.

**Resources:** https://github.com/the-browser-toolbox/docs/actions/new

**Comment by aashu** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by adityabisoi** [comment]
@aashu Add manifest first

**Comment by aashu** [comment]
@adityabisoi I have added a PR #9  with manifest. please take a look into that . after that i would like to work on this issue
