### ISSUE TITLE
Add logic for monitoring website usage

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/usage-monitor#7]
Add logic for monitoring the time spent on a particular website. The countdown timer should stop when the user closes the website, and then resume on further visiting.

To be done after issue #6 is resolved.

**Comment by SaamiraYasmin** [comment]
Hello! I would like to work on this issue. Please assign it to me.

**Comment by adityabisoi** [comment]
@SY0800 tell me your approach.

**Comment by aashu** [comment]
is it still available?

**Comment by adityabisoi** [comment]
@SY0800 Hasn't been active. @aashu Tell me your approach if you want to work on this.

**Comment by aashu** [comment]
i was thinking of using chrome.tabs on changed  and page visibility api to track when either the visibility is changed or new url or tab is opened .. then store it using chrome storage api.. @adityabisoi

**Comment by aashu** [comment]
@adityabisoi check #12 when you are free. some changes might be required

i was thinking of a seperate issue for updating popup page with option to reset data and showing only top10 sites and
current site usage

**Comment by adityabisoi** [comment]
@aashu Sure, let me review the PR today first. Then, create new issues regarding those awesome enhancements.
