### ISSUE TITLE
Add linting and formatting

### ISSUE THREAD

**Issue by adityabisoi** [the-browser-toolbox/usage-monitor#8]
For consistency in styling, linters, and code formatters are used. The most popular ones for JavaScript are `ESLint` and `Prettier`.
Add linting and formatting support to the project.

**Tip:** Use the configuration files and scripts at https://gitlab.com/adityabisoi/aossie-scholar

**Comment by aashu** [comment]
I would like to work on this.please assign it to me

**Comment by adityabisoi** [comment]
@aashu This issue should be resolved after previous ones.

**Comment by aashu** [comment]
I guess all previous issues are resolved. So Can i work on this issue now?
